[tool.poetry]
name = "catedral"
version = "0.1.0"
description = ""
authors = ["Renato Crudo <renato.almeida@soupilar.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.111.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
