services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - .env.development
    ports:
      - "5432:5432"

  samba:
    build: "samba/."
    ports:
      - 8001:8001

  nginx:
    image: nginx
    volumes:
      - './etc/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - 80:80
    depends_on:
      - samba